name: Firebase App Distribution

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build and Distribute APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo "$ENCODED_KEYSTORE" | base64 --decode > app/keystore.jks

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Build APK Location
        run: find app/build/outputs/ -type f

      - name: Upload APK to Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotes: "Versión: 1.0.${{ github.run_number }} - Commit: ${{ github.sha }}"